### ISSUE TITLE
wyproxy存储的数据为什么不用mongo或者mysql json呢？

### ISSUE THREAD

**Issue by lietdai** [ring04h/fpymysql#1]
存储的数据直接用mitmproxy中的HTTPRequest，HTTPResponse类**dict**数据格式，需要处理时初始化一个HTTPRequest或者HTTPResponse，利用里面的方法省去写很多utils

**Comment by ring04h** [comment]
最后的结果要给扫描器用的，排除掉一些没意义的资源，还有页面的spider，
都需要结构化的数据，将来做统计分析。

**Comment by ring04h** [comment]
现在做了新的架构更新，第一时间在main 执行周期parser了入库，会损耗掉一部分效率，
新的做法是，直接将 HTTPRequest, HTTPResponse, 序列化了存到临时数据库，再后台开一个parser守护进程，来分析临时数据，生成可分析的对象。
